# GitHub Actions CI/CD Pipeline
# Copy to .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# Cancel in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.12'

jobs:
  # =============================================================================
  # Lint & Type Check
  # =============================================================================
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Node.js setup (uncomment if needed)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      
      # - name: Install dependencies
      #   run: npm ci
      
      # - name: Run ESLint
      #   run: npm run lint
      
      # - name: Run TypeScript check
      #   run: npx tsc --noEmit
      
      # Python setup (uncomment if needed)
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      #     cache: 'pip'
      
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      
      # - name: Run Ruff
      #   run: ruff check .
      
      # - name: Run MyPy
      #   run: mypy .

  # =============================================================================
  # Tests
  # =============================================================================
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    
    # Database service (uncomment if needed)
    # services:
    #   postgres:
    #     image: postgres:15
    #     env:
    #       POSTGRES_USER: test
    #       POSTGRES_PASSWORD: test
    #       POSTGRES_DB: test
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      # Node.js setup (uncomment if needed)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      
      # - name: Install dependencies
      #   run: npm ci
      
      # - name: Run tests
      #   run: npm test
      #   env:
      #     DATABASE_URL: postgresql://test:test@localhost:5432/test
      
      # Python setup (uncomment if needed)
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}
      #     cache: 'pip'
      
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      
      # - name: Run tests
      #   run: pytest --cov=src --cov-report=xml
      
      # - name: Upload coverage
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./coverage.xml

  # =============================================================================
  # Build
  # =============================================================================
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      # Node.js build (uncomment if needed)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ env.NODE_VERSION }}
      #     cache: 'npm'
      
      # - name: Install dependencies
      #   run: npm ci
      
      # - name: Build
      #   run: npm run build
      
      # Docker build (uncomment if needed)
      # - name: Build Docker image
      #   run: docker build -t app:${{ github.sha }} .
      
      # - name: Push to registry
      #   run: |
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker push app:${{ github.sha }}

  # =============================================================================
  # Deploy (uncomment and customize)
  # =============================================================================
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   environment: production
  #   
  #   steps:
  #     - uses: actions/checkout@v4
  #     
  #     - name: Deploy to production
  #       run: |
  #         # Add deployment commands here
  #         echo "Deploying to production..."
